### ISSUE TITLE
The problem is the theme.

### ISSUE THREAD

**Issue by dursuntokgoz** [auxio/CstyleX#1]
Because the bootstrap is not working on the modules, the wrong screen image appears. For example, the DNS Management module page. Thx u.

**Comment by Ron-e** [comment]
I do not understand what you mean. can you tell me more clearly what problem you are having?

**Comment by Ron-e** [comment]
If you are referring to that the standard dns manager in Sentora does not display properly, you are right.
That's why i made a non bootstrap version/ported the old dns manager to Sentora which you can find as CDNS manager -> https://github.com/auxio/cdns_manager
Please let me know if this solved the problem so i can close or solve the problem.

**Comment by dursuntokgoz** [comment]
You have an error on all modules created using bootstrap. For example, no records are added to the DNS Management module.

**Comment by Ron-e** [comment]
please be more clear, i only have problems with the dns manager, that's why i have the non bootstrap version called CDNS manager, have you tried it?
What other modules have problems?

**Comment by dursuntokgoz** [comment]
this error information
http://i.hizliresim.com/GPMDZ2.jpg

**Comment by Ron-e** [comment]
Have you read the README file? it Clearly stated: "The v3 is an ported version of an ported version of the the original version, so it is a mess but it works on my special Sentora development VPS. It does not confirm to the new standardization policy of Sentora and NO support will be given for this theme! I made this ONLY to look if it s still possible to port this theme to Sentora v1.0.0 BETA and it can be done..".
So please do not expect a perfect working theme, you can fork and work on it to make it bootstrap compatible.
